name: veridex-prod

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: veridex_backend
    restart: always
    env_file:
      - .env.production
    ports:
      - "8000:8000"
    depends_on:
      opa:
        condition: service_started

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: veridex_worker
    restart: always
    command: uv run celery -A app.workers.celery_app worker --loglevel=info -Q celery,planner_queue,agent_queue,ingestion_queue
    env_file:
      - .env.production
    depends_on:
      opa:
        condition: service_started
      backend:
        condition: service_started

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: veridex_frontend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    depends_on:
      - backend
      
  opa:
    image: openpolicyagent/opa:latest
    container_name: veridex_opa
    restart: always
    ports:
      - "8181:8181"
    command:
      - "run"
      - "--server"
      - "--addr"
      - ":8181"
      - "/policies"
    volumes:
      - ./backend/app/governance/policies:/policies
