"""Add MFA fields and fix UUIDs

Revision ID: 1d2894a46f12
Revises: f543dc9ff8ba
Create Date: 2026-07-24 17:28:10.272129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.models.connector



# revision identifiers, used by Alembic.
revision: str = '1d2894a46f12'
down_revision: Union[str, Sequence[str], None] = 'f543dc9ff8ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_logs_created_at'), 'ai_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_logs_id'), 'ai_logs', ['id'], unique=False)
    op.create_index(op.f('ix_ai_logs_model'), 'ai_logs', ['model'], unique=False)
    op.create_index(op.f('ix_ai_logs_task_id'), 'ai_logs', ['task_id'], unique=False)
    op.create_table('login_audit_logs',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('email_attempted', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_audit_logs_email_attempted'), 'login_audit_logs', ['email_attempted'], unique=False)
    op.create_index(op.f('ix_login_audit_logs_timestamp'), 'login_audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_login_audit_logs_user_id'), 'login_audit_logs', ['user_id'], unique=False)
    op.create_table('chat_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('traces', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_history_id'), 'chat_history', ['id'], unique=False)
    op.create_index(op.f('ix_chat_history_thread_id'), 'chat_history', ['thread_id'], unique=False)
    op.create_table('connector_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('config_data', app.db.models.connector.EncryptedJSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connector_configs_id'), 'connector_configs', ['id'], unique=False)
    op.create_table('evaluation_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dataset_name', sa.String(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('average_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_runs_id'), 'evaluation_runs', ['id'], unique=False)
    op.add_column('users', sa.Column('mfa_secret', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('mfa_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('tos_accepted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('privacy_accepted', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'privacy_accepted')
    op.drop_column('users', 'tos_accepted')
    op.drop_column('users', 'mfa_enabled')
    op.drop_column('users', 'mfa_secret')
    op.drop_index(op.f('ix_evaluation_runs_id'), table_name='evaluation_runs')
    op.drop_table('evaluation_runs')
    op.drop_index(op.f('ix_connector_configs_id'), table_name='connector_configs')
    op.drop_table('connector_configs')
    op.drop_index(op.f('ix_chat_history_thread_id'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_id'), table_name='chat_history')
    op.drop_table('chat_history')
    op.drop_index(op.f('ix_login_audit_logs_user_id'), table_name='login_audit_logs')
    op.drop_index(op.f('ix_login_audit_logs_timestamp'), table_name='login_audit_logs')
    op.drop_index(op.f('ix_login_audit_logs_email_attempted'), table_name='login_audit_logs')
    op.drop_table('login_audit_logs')
    op.drop_index(op.f('ix_ai_logs_task_id'), table_name='ai_logs')
    op.drop_index(op.f('ix_ai_logs_model'), table_name='ai_logs')
    op.drop_index(op.f('ix_ai_logs_id'), table_name='ai_logs')
    op.drop_index(op.f('ix_ai_logs_created_at'), table_name='ai_logs')
    op.drop_table('ai_logs')
    # ### end Alembic commands ###
