"""Add swarm_config to project

Revision ID: e2f0140b85c4
Revises: 0c34e4998a38
Create Date: 2026-07-31 23:16:35.210922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2f0140b85c4'
down_revision: Union[str, Sequence[str], None] = '0c34e4998a38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('swarm_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'swarm_config')
    # ### end Alembic commands ###
